import { useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "./ui/dialog";
import { Button } from "./ui/button";
import { Badge } from "./ui/badge";
import { Card, CardContent } from "./ui/card";
import { MapPin, Clock, Mountain, Navigation, Eye, EyeOff } from "lucide-react";
import RouteMap from "./RouteMap";

const RouteMapModal = ({ isOpen, onClose, hikeData }) => {
  const [showWaypoints, setShowWaypoints] = useState(true);
  const [selectedWaypoint, setSelectedWaypoint] = useState(null);

  // Calculate route statistics
  const routeStats = {
    totalDistance: hikeData?.distance || 0,
    totalWaypoints: hikeData?.waypoints?.length || 0,
    duration: hikeData?.duration || 0,
    elevation: hikeData?.elevation || 0
  };

  // Render the real map with waypoints
  const renderMapVisualization = () => {
    return (
      <RouteMap 
        waypoints={hikeData?.waypoints || []} 
        gpsTrack={hikeData?.gpsTrack || []}
        hikeData={hikeData}
      />
    );
  };

  const renderWaypointsList = () => {
    // Only show manually added waypoints and start/end points, not auto-generated GPS points
    const manualWaypoints = hikeData?.waypoints?.filter(wp => !wp.autoGenerated || wp.isStartPoint || wp.isEndPoint) || [];
    if (manualWaypoints.length === 0) {
      return null;
    }

    return (
      <div className="space-y-3 max-h-48 overflow-y-auto">
        {manualWaypoints.map((waypoint, index) => (
          <Card 
            key={index} 
            className={`cursor-pointer transition-colors ${
              selectedWaypoint === index ? 'bg-muted border-border' : 'hover:bg-muted/50'
            }`}
            onClick={() => setSelectedWaypoint(selectedWaypoint === index ? null : index)}
          >
            <CardContent className="p-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className={`w-3 h-3 rounded-full ${
                    index === 0 ? 'bg-green-600' : 
                    index === manualWaypoints.length - 1 ? 'bg-red-600' : 'bg-blue-500'
                  }`}></div>
                  <div>
                    <div className="font-medium text-sm">
                      {index === 0 ? 'Start Point' : 
                       index === manualWaypoints.length - 1 ? 'End Point' : 
                       `Waypoint ${index + 1}`}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      {waypoint.timestamp ? new Date(waypoint.timestamp).toLocaleTimeString() : 'Unknown time'}
                    </div>
                  </div>
                </div>
                <div className="text-right">
                  <div className="text-xs text-muted-foreground">
                    {waypoint.latitude?.toFixed(6)}, {waypoint.longitude?.toFixed(6)}
                  </div>
                  {waypoint.altitude && (
                    <div className="text-xs text-muted-foreground">
                      {Math.round(waypoint.altitude * 3.28084)} ft
                    </div>
                  )}
                </div>
              </div>
              
              {selectedWaypoint === index && (
                <div className="mt-3 pt-3 border-t border-border">
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 sm:gap-4 text-xs">
                    <div>
                      <span className="font-medium">Latitude:</span> {waypoint.latitude?.toFixed(6)}
                    </div>
                    <div>
                      <span className="font-medium">Longitude:</span> {waypoint.longitude?.toFixed(6)}
                    </div>
                    {waypoint.altitude && (
                      <div>
                        <span className="font-medium">Elevation:</span> {Math.round(waypoint.altitude * 3.28084)} ft
                      </div>
                    )}
                    {waypoint.distance && (
                      <div>
                        <span className="font-medium">Distance:</span> {waypoint.distance.toFixed(1)} km
                      </div>
                    )}
                  </div>
                  {waypoint.notes && (
                    <div className="mt-2">
                      <span className="font-medium text-xs">Notes:</span>
                      <p className="text-xs text-muted-foreground mt-1">{waypoint.notes}</p>
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        ))}
      </div>
    );
  };

  return (
    <Dialog open={isOpen} onOpenChange={onClose}>
      <DialogContent className="w-[95vw] max-w-[800px] max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="text-xl sm:text-2xl text-foreground flex items-center gap-2">
            <MapPin className="h-5 w-5 sm:h-6 sm:w-6 text-summit" />
            <span className="truncate">{hikeData?.title} - Route Map</span>
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-4 sm:space-y-6">
          {/* Route Statistics */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 sm:gap-4">
            <Card className="bg-gradient-card text-center border-border">
              <CardContent className="p-3 sm:p-4">
                <div className="text-xl sm:text-2xl font-bold text-forest">{routeStats.totalWaypoints}</div>
                <div className="text-xs sm:text-sm text-muted-foreground">Waypoints</div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-card text-center border-border">
              <CardContent className="p-3 sm:p-4">
                <div className="text-xl sm:text-2xl font-bold text-trail">{routeStats.totalDistance}</div>
                <div className="text-xs sm:text-sm text-muted-foreground">km</div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-card text-center border-border">
              <CardContent className="p-3 sm:p-4">
                <div className="text-xl sm:text-2xl font-bold text-summit">{routeStats.elevation}</div>
                <div className="text-xs sm:text-sm text-muted-foreground">Elevation (ft)</div>
              </CardContent>
            </Card>
            <Card className="bg-gradient-card text-center border-border">
              <CardContent className="p-3 sm:p-4">
                <div className="text-xl sm:text-2xl font-bold text-forest">{routeStats.duration}</div>
                <div className="text-xs sm:text-sm text-muted-foreground">Duration</div>
              </CardContent>
            </Card>
          </div>

          {/* Map Visualization */}
          {renderMapVisualization()}

          {/* Waypoints List */}
          <div>
            <div className="flex items-center justify-between mb-3 sm:mb-4">
              <h3 className="text-base sm:text-lg font-semibold text-foreground flex items-center gap-2">
                <Navigation className="h-4 w-4 sm:h-5 sm:w-5" />
                <span className="hidden sm:inline">GPS Waypoints</span>
                <span className="sm:hidden">Waypoints</span>
              </h3>
              <Button
                variant="outline"
                size="sm"
                onClick={() => setShowWaypoints(!showWaypoints)}
                className="flex items-center gap-1 sm:gap-2 min-h-[44px] min-w-[44px]"
              >
                {showWaypoints ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}
                <span className="hidden sm:inline">{showWaypoints ? 'Hide' : 'Show'} Details</span>
              </Button>
            </div>
            
            {showWaypoints && renderWaypointsList()}
          </div>

          {/* Additional Info */}
          {hikeData?.notes && (
            <Card className="bg-gradient-subtle border-border">
              <CardContent className="p-4">
                <h3 className="font-semibold text-foreground mb-2">Hike Notes</h3>
                <p className="text-muted-foreground">{hikeData.notes}</p>
              </CardContent>
            </Card>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
};

export default RouteMapModal;

