name: CI Pipeline

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # 3. Install root dependencies (for husky etc.)
      - name: Install root dependencies
        run: npm install

      # ---- FRONTEND ----
      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Lint frontend
        working-directory: frontend
        run: npm run lint 

      - name: Run frontend tests
        working-directory: frontend
        run: npm test -- --coverage

      # ---- BACKEND ----
      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Lint backend
        working-directory: backend
        run: npm run lint 

      - name: Run backend tests
        working-directory: backend
        run: npm test -- --coverage


      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: backend/coverage/lcov.info,frontend/coverage/lcov.info
            slug: Hikers-for-life/Hiking-Logbook
